#!/bin/sh

# Simple script to execute java with the appropriate options to run Mauve.
# (c) 2003 Aaron Darling

# Change `java` to the location of your java binary if necessary.
# Change the values of the `-Xms` and `-Xmx` parameters if you are getting
# out of memory errors.
# Change MAUVE_DIR to the path where the root directory of Mauve is (which
# should also include Mauve.jar)

MAUVE_DIR="$(dirname $0)/.."

java -Xms256M -Xmx4G -DmauveDir=$MAUVE_DIR -jar $MAUVE_DIR/Mauve.jar $@
